apiVersion: v1
kind: Pod
metadata:
  name: nodejs-ci-test
spec:
  containers:
    - name: nodejs
      image: node:20
      command: ["sh", "-c", "npm install && npm run lint && npm test"]
      volumeMounts:
        - name: app-code
          mountPath: /usr/src/app
      workingDir: /usr/src/app
  restartPolicy: Never
  volumes:
    - name: app-code
      hostPath:
        path: /path/to/your/app
        type: Directory
